name: nlp-ai-skills
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.6.6
  - conda-forge::pyodbc
  - conda-forge::spacy==2.0.12
  - pyopenssl
  - pandas
  - azure-storage-blob
  - scikit-learn 
  - matplotlib